<a href="https://colab.research.google.com/github/TheMShahid/00_PyTorch_Fundamentals_By_Muhammad_Shahid_Khan/blob/main/00_pytorch_fundamentals_video_aug_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Learning PyTorch Again 1 Aug 2025 Fri, 8:40 AM School Time Morning')

Learning PyTorch Again 1 Aug 2025 Fri, 8:40 AM School Time Morning


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## 00. Pytorch Fundamentals

Rsource notebook:

If you have any question:

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating tensors

PyTorch tensors are creating using `torch.Tensor()` =

In [ ]:
# Scalar
scalar = torch.tensor(1)
scalar

tensor(1)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
# Get tensor back as Python Int
scalar.item()

1

In [ ]:
# Vector
vector = torch.tensor([2, 2])
vector

tensor([2, 2])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[1, 2],
                       [3, 5]])
MATRIX

tensor([[1, 2],
        [3, 5]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[0][1]

tensor([4, 5, 6])

In [ ]:
TENSOR[0][1][1]

tensor(5)

### Random tensors

Whey random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better repesent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3470, 0.2869, 0.2093, 0.9942],
        [0.0548, 0.7298, 0.4666, 0.6750],
        [0.7566, 0.6825, 0.7933, 0.7339]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_tensor2 = torch.rand(2, 3, 4)
random_tensor2

tensor([[[0.4780, 0.4978, 0.4761, 0.8767],
         [0.3799, 0.7834, 0.7769, 0.5330],
         [0.5404, 0.7462, 0.2387, 0.1887]],

        [[0.3006, 0.1980, 0.1835, 0.0066],
         [0.0851, 0.2911, 0.4893, 0.0824],
         [0.4483, 0.0380, 0.5401, 0.7272]]])

In [ ]:
random_tensor2.ndim

3

In [ ]:
random_tensor2.shape

torch.Size([2, 3, 4])

In [ ]:
random_tensor3 = torch.rand(3, 5, 5)
random_tensor3

tensor([[[0.1316, 0.5001, 0.6083, 0.3016, 0.9245],
         [0.7226, 0.1535, 0.8402, 0.1534, 0.6511],
         [0.9617, 0.3878, 0.3253, 0.9856, 0.8068],
         [0.4626, 0.4909, 0.0283, 0.4418, 0.3217],
         [0.8102, 0.2195, 0.1272, 0.7307, 0.9448]],

        [[0.8510, 0.2124, 0.0200, 0.6252, 0.3926],
         [0.4471, 0.9626, 0.4073, 0.3330, 0.5201],
         [0.0425, 0.7032, 0.7050, 0.5323, 0.0778],
         [0.9940, 0.2336, 0.8685, 0.5277, 0.8139],
         [0.3145, 0.0651, 0.8306, 0.9946, 0.3163]],

        [[0.4314, 0.3088, 0.6625, 0.8302, 0.7321],
         [0.0717, 0.9021, 0.7128, 0.0039, 0.1051],
         [0.4710, 0.3223, 0.5509, 0.9141, 0.4177],
         [0.9806, 0.1680, 0.0664, 0.8771, 0.4145],
         [0.3999, 0.9307, 0.6631, 0.7821, 0.8591]]])

In [ ]:
random_tensor3.ndim

3

In [ ]:
random_tensor3.shape

torch.Size([3, 5, 5])

In [ ]:
random_tensor4 = torch.rand(4, 2, 2)
random_tensor4

tensor([[[0.1302, 0.4318],
         [0.2643, 0.6893]],

        [[0.2831, 0.7668],
         [0.2867, 0.5909]],

        [[0.1743, 0.7952],
         [0.0729, 0.6004]],

        [[0.4915, 0.6867],
         [0.4767, 0.0603]]])

In [ ]:
random_tensor4.shape

torch.Size([4, 2, 2])

In [ ]:
random_tensor4.ndim

3

In [ ]:
random_tensor5 = torch.rand(2, 2, 2, 2)
random_tensor5

tensor([[[[0.3230, 0.7500],
          [0.5826, 0.1700]],

         [[0.7372, 0.2159],
          [0.4169, 0.4159]]],


        [[[0.3265, 0.2282],
          [0.4826, 0.6799]],

         [[0.3940, 0.9081],
          [0.6541, 0.3007]]]])

In [ ]:
random_tensor5.ndim

4

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

### Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all Ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range tensors and tensors-like


In [ ]:
# Use torch.range(), torch.arange()
torch.range(5, 11), torch.arange(10, 21)

/tmp/ipython-input-2261503806.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(5, 11), torch.arange(10, 21)


(tensor([ 5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]))

In [ ]:
five_to_fiften = torch.arange(5, 16)
five_to_fiften

tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
start, end, step = 0, 20, 3
zero_to_20_step_3 = torch.arange(start, end, step)
zero_to_20_step_3

tensor([ 0,  3,  6,  9, 12, 15, 18])

In [ ]:
zero_to_10_step_2 = torch.arange(start=0, end=10, step=2)
zero_to_10_step_2

tensor([0, 2, 4, 6, 8])

In [ ]:
zero_to_500_step_20 = torch.arange(start=0, end=500, step=20 )
zero_to_500_step_20

tensor([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200, 220, 240, 260,
        280, 300, 320, 340, 360, 380, 400, 420, 440, 460, 480])

In [ ]:
# Creating tensors like
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
twenty_to_50 = torch.arange(start=20, end=51, step=5)
twenty_to_50

tensor([20, 25, 30, 35, 40, 45, 50])

In [ ]:
fifty_zeros = torch.zeros_like(input=twenty_to_50)
fifty_zeros

tensor([0, 0, 0, 0, 0, 0, 0])

### Tensors Datatypes


**Note**: Tensors datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning

1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing -

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([2.0, 4.0, 6.0], dtype=None)
float_32_tensor

tensor([2., 4., 6.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16, # What dataype is the tensor (e.g. float32, float16)
                               device=None, # cpu, cuda. What device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations.
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_64_tensor = torch.tensor([1.0, 2.0, 3.0],
                               dtype=torch.float64,
                               device=None,
                               requires_grad=False)
float_64_tensor

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
float_64_tensor.dtype

torch.float64

In [ ]:
# How to change the tensors datatypes
from_float_64_tensor_to_float_32_tensor = float_64_tensor.type(torch.float32)
from_float_64_tensor_to_float_32_tensor, from_float_64_tensor_to_float_32_tensor.dtype

(tensor([1., 2., 3.]), torch.float32)

In [ ]:
from_float_32_tensor_to_half = from_float_64_tensor_to_float_32_tensor.type(torch.half)
from_float_32_tensor_to_half

tensor([1., 2., 3.], dtype=torch.float16)

In [ ]:
# Here is the both tensors datatypes is the same, but the number is different so this will work, no errors
float_64_tensor * float_16_tensor

tensor([ 3., 12., 27.], dtype=torch.float64)

In [ ]:
int_32_tensor = torch.tensor([1, 2, 3],
                             dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
float_16_tensor * int_32_tensor

tensor([ 3., 12., 27.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)

1. Tensors not right datatypes - to do get datatypes from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to do get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to do get device from a tensor, can use `tensor.device`

In [ ]:
# Creat a tensor
some_random_tensor = torch.rand(4, 4)
some_random_tensor

tensor([[0.3180, 0.8963, 0.7759, 0.4445],
        [0.1460, 0.3147, 0.2186, 0.2530],
        [0.1424, 0.3552, 0.3191, 0.0874],
        [0.2494, 0.6136, 0.3082, 0.4909]])

In [ ]:
some_random_tensor.size(), some_random_tensor.shape # both are the same things one is method size(), and the other is attribute .shape()

(torch.Size([4, 4]), torch.Size([4, 4]))

In [ ]:
# Find out details about some random tensor
print(some_random_tensor)
print(f'Datatype of tensor: {some_random_tensor.dtype}')
print(f'Shape of a tensor: {some_random_tensor.shape}')
print(f'Device of a tensor: {some_random_tensor.device}')
print(f'Deminsions of a tensor: {some_random_tensor.ndim}')

tensor([[0.3180, 0.8963, 0.7759, 0.4445],
        [0.1460, 0.3147, 0.2186, 0.2530],
        [0.1424, 0.3552, 0.3191, 0.0874],
        [0.2494, 0.6136, 0.3082, 0.4909]])
Datatype of tensor: torch.float32
Shape of a tensor: torch.Size([4, 4])
Device of a tensor: cpu
Deminsions of a tensor: 2


### Manipulating Tensors (tensors operations)

Tensors operations include:
* Addition
* Subtractin
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 5 to it
tensor = torch.tensor([2, 4, 6])
tensor + 5

tensor([ 7,  9, 11])

In [ ]:
# Multiply tensor by 5
tensor * 5

tensor([10, 20, 30])

In [ ]:
tensor

tensor([2, 4, 6])

In [ ]:
# Subtract 5 from tensor
tensor - 5

tensor([-3, -1,  1])

In [ ]:
# Try out PyTorch in-build functions
torch.mul(tensor, 5)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 5)

tensor([ 7,  9, 11])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - (mathsisfun.com)

There are three main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 2)`

In [ ]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2)) # not work
torch.matmul(torch.rand(2, 3), torch.rand(3, 2)) # valid

tensor([[0.3245, 0.1536],
        [1.0876, 1.0590]])

In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.6236, 0.6353, 0.5793],
        [0.8682, 0.9007, 0.8167],
        [0.3624, 0.3004, 0.2934]])

In [ ]:
torch.matmul(torch.rand(3, 5), torch.rand(5, 3))

tensor([[1.7968, 1.5887, 1.6204],
        [1.7189, 1.4597, 1.4713],
        [1.8469, 2.1027, 1.8427]])

In [ ]:
torch.matmul(torch.rand(8, 8), torch.rand(8, 8)).shape

torch.Size([8, 8])

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f'Equals: {tensor * tensor}')

tensor([2, 4, 6]) * tensor([2, 4, 6])
Equals: tensor([ 4, 16, 36])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(56)

In [ ]:
tensor

tensor([2, 4, 6])

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(56)
CPU times: user 1.47 ms, sys: 77 µs, total: 1.54 ms
Wall time: 8.93 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 118 µs, sys: 0 ns, total: 118 µs
Wall time: 2.13 ms


tensor(56)

### One of the most common erros in deep learning shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 3],
                        [5, 7],
                        [9, 11]])
tensor_B = torch.tensor([[2, 4],
                        [6, 8],
                        [10, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul(it's an alias for writing less code)
# torch.matmul(tensor_A, tensor_B)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensors shape issues, we can manipulate the shape of a one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 2,  4],
         [ 6,  8],
         [10, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 2,  6, 10],
         [ 4,  8, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B = {tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match')
print('Output:\n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput shape: {output.shape}')

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 14,  30,  46],
        [ 38,  86, 134],
        [ 62, 142, 222]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
# torch.mean(x)
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Find the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> and then returns the index position of a target tensor where the minimum vlaue occurs.
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
# Find the position in tensor that has the maximum value with argmax() -> and then retunrs the index position of a target tensor where the maximum value occurs.
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of a certain shape, but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a targert tensor
* Permute - Return a view of the input with dimension permuted. (swapped) in a certain way

In [ ]:
# Let's creat a tensor
import torch
x = torch.arange(1., 10.)
# x = torch.arange(1., 11.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
# x_reshaped = x.reshape(1, 7)
x_reshaped = x.reshape(1, 9)
# x_reshaped = x.reshape(2, 9)
# x_reshaped = x.reshape(9, 1)
# x_reshaped = x.reshape(5, 2)
# x_reshaped = x.reshape(2, 5)

x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Changing z changing x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 10
z, x

(tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [ ]:
# Stack tensors on the top of each other
y_stacked = torch.stack([x, x, x, x], dim=0) # for ystack dim 0
x_stacked = torch.stack([x, x, x, x], dim=1) # for xstack dim 1

x_stacked, y_stacked

(tensor([[10., 10., 10., 10.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.]]),
 tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]))

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped

tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()

tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f'Previous target tensor: {x_squeezed}')
print(f'Previous target tensor shape: {x_squeezed.shape}')

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target tensor: tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])
Previous target tensor shape: torch.Size([9])

New tensor: tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order.
x_original = torch.rand(size=(224, 224, 3))
x_original

tensor([[[0.6763, 0.3711, 0.0386],
         [0.8844, 0.6485, 0.2437],
         [0.1784, 0.4225, 0.3152],
         ...,
         [0.0325, 0.1281, 0.0734],
         [0.5077, 0.4738, 0.4900],
         [0.3568, 0.2873, 0.3722]],

        [[0.5268, 0.4898, 0.8967],
         [0.0806, 0.5926, 0.0280],
         [0.8269, 0.8740, 0.8271],
         ...,
         [0.6165, 0.0509, 0.1225],
         [0.2876, 0.9960, 0.5163],
         [0.2577, 0.5937, 0.9618]],

        [[0.0923, 0.8512, 0.0828],
         [0.3984, 0.1845, 0.8928],
         [0.2675, 0.1232, 0.5149],
         ...,
         [0.3751, 0.7502, 0.9280],
         [0.4741, 0.9961, 0.5504],
         [0.9408, 0.3966, 0.1857]],

        ...,

        [[0.6202, 0.5438, 0.8439],
         [0.9273, 0.1493, 0.1790],
         [0.9516, 0.6928, 0.9941],
         ...,
         [0.1317, 0.7087, 0.9877],
         [0.6523, 0.8040, 0.9831],
         [0.5373, 0.8878, 0.7046]],

        [[0.3784, 0.9406, 0.5500],
         [0.6401, 0.3219, 0.5016],
         [0.

In [ ]:
# Permute the original tensor to rearranges the axis or (dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}')

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0], x_permuted[0, 0, 0], x_original.ndim

(tensor(0.6763), tensor(0.6763), 3)

In [ ]:
x_original[0, 0, 0] = 7777

In [ ]:
x_original[0, 0, 0]

tensor(7777.)

In [ ]:
x_permuted[0, 0, 0]

tensor(7777.)

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the first bracket (dim=1)
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
# Let's index on the first bracket and second element -> 3
x[0][0][2], x[0, 0, 2]

(tensor(3), tensor(3))

In [ ]:
x[0, 1, 1],

(tensor(5),)

In [ ]:
x[0, 2, 2]

tensor(9)

In [ ]:
# You can also use ":" to select all of a target tensor dimension
x[:, 0], x[:, 2], x[:, 2, 2]

(tensor([[1, 2, 3]]), tensor([[7, 8, 9]]), tensor([9]))

In [ ]:
x[1:, 0, 0]

tensor([], dtype=torch.int64)

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of second dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 0]

tensor([4])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1], x[0, 1, 1]

(tensor([5]), tensor(5))

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of second dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
x[0, 2, 2]

tensor(9)

In [ ]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, Python has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) # warning: when converting from numpy -> PyTorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
tensor.dtype

torch.float32

In [ ]:
array.dtype

dtype('float64')

In [ ]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
# Change the value of array, what will this do to `tensor`?
array = array + 1;
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to `numpy_tensor`
numpy_tensor += 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> look at data -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again ...`

To reduce the randomness in neural networks and PyTorch comes with the concept of **random seed**.

Essentially what the random seed does is "flavor" the randomness.

In [ ]:
torch.rand(3, 3) # how many time you run this line or this cell every time you will be get a random number

tensor([[0.3859, 0.8372, 0.0084],
        [0.3077, 0.5691, 0.5496],
        [0.7794, 0.4362, 0.3605]])

In [ ]:
import torch

# Create two random tensor
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4891, 0.9729, 0.9510, 0.8911],
        [0.7670, 0.6634, 0.5770, 0.2692],
        [0.7010, 0.0975, 0.8102, 0.1712]])
tensor([[0.3257, 0.8479, 0.5457, 0.6501],
        [0.9122, 0.6988, 0.5854, 0.6087],
        [0.0253, 0.6804, 0.3104, 0.5069]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Extra resources for reproducibility
* pytorchrandomness

## Runing tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing GPU, ther's a lots of options...
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them.

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code

E.g. run on GPU if available, else default to CPU.

In [ ]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [ ]:
# Count number of devices
torch.cuda.device_count()

0

## 3. Putting tensors (and models) on the GPU

The reson we want our tensors/models on the GPU is because using GPU results in faster computations

In [ ]:
# Create a tensor (Default on the CPU)
tensor = torch.tensor([1, 2, 3], device="cpu")

# Tensor not on GPU
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back to CPU


In [ ]:
# If tensor is on GPU, can't transform it to NumPy
# tensor_on_gpu.numpy()

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

# 00_PyTorch_fundamentals_exercise

In [ ]:
# Create a ranodm tensor with shape (7, 7)
random_tensor_with_shape_7_7 = torch.rand(7, 7)
random_tensor_with_shape_7_7

tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477],
        [0.6524, 0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331],
        [0.9578, 0.3313, 0.3227, 0.0162, 0.2137, 0.6249, 0.4340],
        [0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816]])

In [ ]:
random_tensor_with_shape_1_7 = torch.rand(1, 7)
random_tensor_with_shape_1_7

tensor([[0.9998, 0.5944, 0.6541, 0.0337, 0.1716, 0.3336, 0.5782]])

In [ ]:
random_tensor_with_shape_7_7.shape, random_tensor_with_shape_1_7.shape

(torch.Size([7, 7]), torch.Size([1, 7]))

In [ ]:
random_tensor_with_shape_7_7.T.shape, random_tensor_with_shape_1_7.T.shape

(torch.Size([7, 7]), torch.Size([7, 1]))

In [ ]:
random_tensor_with_shape_7_7.shape, random_tensor_with_shape_1_7.T.shape

(torch.Size([7, 7]), torch.Size([7, 1]))

In [ ]:
torch.matmul(random_tensor_with_shape_7_7, random_tensor_with_shape_1_7.T)

tensor([[1.2748],
        [1.1652],
        [1.0182],
        [1.7959],
        [1.6076],
        [1.8623],
        [0.7118]])

In [ ]:
random_tensor_7_7_before_the_seed = random_tensor_with_shape_7_7
random_tensor_1_7_before_the_seed = random_tensor_with_shape_1_7

print(f'Random tensor before the random seed {random_tensor_7_7_before_the_seed}')
print(f'Random tensor before the random sedd {random_tensor_1_7_before_the_seed}')

Random tensor before the random seed tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477],
        [0.6524, 0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331],
        [0.9578, 0.3313, 0.3227, 0.0162, 0.2137, 0.6249, 0.4340],
        [0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816]])
Random tensor before the random sedd tensor([[0.9998, 0.5944, 0.6541, 0.0337, 0.1716, 0.3336, 0.5782]])


In [ ]:
import torch

# Set random seed to 0
RANDOM_SEED = torch.manual_seed(0)

random_tensor_7_7 = torch.rand(7, 7)
random_tensor_1_7 = torch.rand(1, 7)

print(f'\nRandom tensor after the random seed {random_tensor_7_7}')
print(f'Random tensor after the random seed {random_tensor_1_7}')


Random tensor after the random seed tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
Random tensor after the random seed tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])


In [ ]:
# Create two random tensors with shape (2, 3)
random_tensor_1 = torch.rand(2, 3)
random_tensor_2 = torch.rand(2, 3)
random_tensor_1, random_tensor_2

(tensor([[0.5932, 0.1123, 0.1535],
         [0.2417, 0.7262, 0.7011]]),
 tensor([[0.2038, 0.6511, 0.7745],
         [0.4369, 0.5191, 0.6159]]))

In [ ]:
random_tensor_1.shape, random_tensor_2.shape, random_tensor_2.reshape(3, 2).shape

(torch.Size([2, 3]), torch.Size([2, 3]), torch.Size([3, 2]))

In [ ]:
random_tensor1_and_2 = torch.mm(random_tensor_1, random_tensor_2.reshape(3, 2))
random_tensor1_and_2

tensor([[0.2876, 0.5298],
        [0.9757, 0.9064]])

In [ ]:
torch.min(random_tensor1_and_2), random_tensor1_and_2.min()

(tensor(0.2876), tensor(0.2876))

In [ ]:
torch.max(random_tensor1_and_2), random_tensor1_and_2.max()

(tensor(0.9757), tensor(0.9757))

In [ ]:
random_tensor_3 = torch.rand(1, 1, 1, 10)
random_tensor_3.shape

torch.Size([1, 1, 1, 10])